README.md
=> Added AppVeyor badge

tomlkit/items.py
Here is the pull request that addresses #40. Let me know if there is anything else you need me to do!
=> When subtracting two Date objects, a timedelta object is returned.

CHANGELOG.md, README.md, poetry.lock, pyproject.toml, tomlkit/__init__.py
- Added support for heterogeneous arrays ([#92](https://github.com/sdispater/tomlkit/pull/92)).
=> Release 0.6.0

.github/workflows/release.yml, pyproject.toml
=> Fix package release

CHANGELOG.md, pyproject.toml, tomlkit/__init__.py
- Fixed an error where container's data were lost when copying. ([#126](https://github.com/sdispater/tomlkit/pull/126))
- Fixed missing tests in the source distribution of the package. ([#127](https://github.com/sdispater/tomlkit/pull/127))
=> Release 0.7.2

CHANGELOG.md, tests/test_write.py, tomlkit/_utils.py, tomlkit/items.py
=> Escape characters in double quoted key string

CHANGELOG.md, tests/test_items.py, tomlkit/items.py
=> Support table-copy

.github/workflows/integration.yml
=> Add integration tests with Poetry

CHANGELOG.md, tests/test_api.py, tomlkit/api.py, tomlkit/container.py, tomlkit/items.py, tomlkit/parser.py
=> Support adding item with dotted key

CHANGELOG.md, tests/test_toml_document.py, tomlkit/container.py
=> Preserve the separator when replacing value

CHANGELOG.md, tests/test_api.py, tomlkit/items.py
=> Dump tuple as array

CHANGELOG.md, tests/test_items.py, tomlkit/items.py
=> Fix the bug that comments are appended with comma when rendering a multiline array

CHANGELOG.md, tests/test_items.py, tomlkit/items.py
=> fix the astimezone the replace methods

CHANGELOG.md, tomlkit/parser.py
=> fix: reraise KeyAlreadyPresent as ParseError

tests/test_items.py, tomlkit/items.py
=> fix: multiline array format broken when adding or deleting items

.github/workflows/tests.yml
=> Cleanup CI for Python 3.11 support

CHANGELOG.md, tomlkit/container.py, tomlkit/items.py
=> fix: unwrap() for container children values

CHANGELOG.md, tests/test_items.py, tomlkit/parser.py
=> fix: parse datetime followed by a space

.github/workflows/release.yml, .github/workflows/tests.yml, tests/test_items.py, tomlkit/items.py
=> fix: the return type is wrong for int +/- float

CHANGELOG.md, tomlkit/__init__.py
=> Release 0.11.7

tomlkit/container.py, tomlkit/items.py
=> Add types to the `append()` methods of the `Table` and `InlineTable` classes

tomlkit/_types.py, tomlkit/container.py, tomlkit/items.py, tomlkit/parser.py, tomlkit/source.py
=> fix: full methods of integer and float

tomlkit/items.py
fixes https://github.com/sdispater/tomlkit/issues/327
=> indent exist check before accessing its property

CHANGELOG.md, tomlkit/container.py
=> fix: -1 index error when setting dotted key

.github/workflows/tests.yml, CHANGELOG.md, tests/test_items.py, tomlkit/items.py
=> fix: Test failures with Python 3.13.0a4: test_dates_behave_like_dates and test_times_behave_like_times

tomlkit/api.py
Adds an example of `tomlkit.dump()` being used
=> [docs] Add tomlkit.dump() example

CHANGELOG.md, tests/test_items.py, tomlkit/items.py
=> fix: Table header missing

CHANGELOG.md, tests/test_items.py, tomlkit/items.py
=> fix: Empty table dumped when number of subtables > 1

CHANGELOG.md, pyproject.toml, tests/test_toml_document.py, tomlkit/__init__.py, tomlkit/container.py
Context: https://github.com/pdm-project/pdm/issues/3103
=> fix: delete keys from out of order table

CHANGELOG.md, tests/test_items.py, tomlkit/items.py
=> feat: add .item() method to retrieve the item object

CHANGELOG.md, tests/test_toml_document.py, tomlkit/container.py
=> fix: add newline indentation after existing items in Container class
