python-poetry/tomlkit

tests/test_items.py, tomlkit/items.py
InlineTable is supposed to be one liner and doesn't support comments in values.
Closes #30
=> Trim comments when setting InlineTable

tests/test_build.py, tomlkit/container.py
The test case demonstrates how it fails when appending a table.
=> Pick the max when there are many indices for a key.

tests/test_toml_document.py, tomlkit/container.py
This PR fixes the behavior of operations on out of order tables.
Fixes #64
=> Fix behavior for out of order tables

tests/examples/table_names_with_string_delimiters.toml, tests/test_api.py, tomlkit/parser.py
=> Fix parse errors when single quotes are present in a table name

tests/examples/json/table_names.json, tests/examples/table_names.toml, tests/test_api.py, tomlkit/parser.py
=> Fix the way table names are parsed

tests/test_toml_document.py, tomlkit/container.py
=> Fix out of order tables dict-like behavior

.travis.yml, tests/test_toml_document.py, tomlkit/container.py
Fixes #80 
Fixes https://github.com/python-poetry/poetry/issues/2110
Supersedes #81
=> Fix containers and out of order tables dict behavior

tests/examples/json/pyproject.json, tests/examples/pyproject.toml, tests/test_toml_document.py, tomlkit/container.py, tomlkit/items.py
Whenever tables were out of orders the tables were not necessarily dumped in the original order.
This PR fixes it.
=> Fix string output order for out of order tables

tests/test_items.py, tomlkit/_compat.py, tomlkit/api.py, tomlkit/items.py
Resolves #93 
This PR fixes an issue where the order of the original dict was not preserved when dumping it.
It also adds the ability to tell TOMLKit to sort keys when dumping by passing `sort_keys=True` to `dumps()`.
=> Fix the default ordering of dicts and add support for sorting keys

CHANGELOG.md, pyproject.toml, tomlkit/__init__.py
- Added support for sorting keys when dumping raw dictionaries by passing `sort_keys=True` to `dumps()` ([#103](https://github.com/sdispater/tomlkit/pull/103)).
- Keys are not longer sorted by default when dumping a raw dictionary but the original order will be preserved ([#103](https://github.com/sdispater/tomlkit/pull/103)).
- Fixed compliance with the 1.0.0rc1 TOML specification ([#102](https://github.com/sdispater/tomlkit/pull/102)).
=> Release 0.7.0

pyproject.toml
Without a `py.typed` file, mypy won't pick up the type hint comments.
=> Add a py.typed file

tests/test_build.py, tests/test_parser.py, tests/test_toml_document.py, tomlkit/_compat.py, tomlkit/container.py, tomlkit/exceptions.py, tomlkit/items.py, tomlkit/parser.py
Resolves #66
Resolves #97
Resolves #98 
Resolves #105 
Resolves #106 
Resolves #113 
Resolves #117
=> Various fixes

CHANGELOG.md, pyproject.toml, tomlkit/__init__.py
- Fixed an error with indent for nested table elements when updating. ([#122](https://github.com/sdispater/tomlkit/pull/122))
- Fixed various issues with dict behavior compliance for containers. ([#122](https://github.com/sdispater/tomlkit/pull/122))
- Fixed an internal error when empty tables were present after existing ones. ([#122](https://github.com/sdispater/tomlkit/pull/122))
- Fixed table representation for dotted keys. ([#122](https://github.com/sdispater/tomlkit/pull/122))
- Fixed an error in top level keys handling when building documents programmatically. ([#122](https://github.com/sdispater/tomlkit/pull/122))
- Fixed compliance with mypy by adding a `py.typed` file. ([#109](https://github.com/sdispater/tomlkit/pull/109))
=> Release 0.7.1

tests/test_toml_document.py, tomlkit/container.py
When reconstructing the container, make sure data are set to the internal `dict`.
Fixes #124
=> Correctly restore data for container

tomlkit/exceptions.py
TOML `\u` unicode literal takes a hex string, but the error message was using `str()`. This results in an incorrect suggestion to users.
=> Fix incorrect InvalidControlChar error message

CHANGELOG.md, tests/test_api.py, tomlkit/api.py
```python
doc = tomlkit.document()
table = tomlkit.table(True)
table.add("bar", {"x": 1})
doc.add("foo", table)
print(doc.as_string())
```
```toml
[foo.bar]
x = 1
```
Intermediate table is hidden.
Fixes #47
=> Add an argument to allow table to be super table

tests/test_api.py, tomlkit/api.py, tomlkit/parser.py, tomlkit/source.py
This included values that strat with `t` or `f` like `test` and `friend` as well as values that have `true` or `false` as prefix like `truely` and `falsely`.
All of them are now incorrectly rejected by `tomlkit.value`.
Closes #165
=> Fix values similar to booleans being incorrectly parsed to booleans

CHANGELOG.md, tests/test_api.py, tomlkit/_utils.py, tomlkit/api.py, tomlkit/exceptions.py, tomlkit/items.py
Hello, it would be interesting to expose a way of controlling the string style (e.g. allowing multi line strings).
This PR is an attempt to provide such API.
I ended up going for a very verbose API (with explicit keywords) because I believe that it is easier to use, but please let me know if you prefer exposing `StringType` as part of the public API.
I think this closes #44.
=> Allow string type to be controlled from the public API

CHANGELOG.md, tests/test_toml_document.py, tomlkit/container.py
=> Fix: Add newline before super tables when rendering

README.md
=> Fix a trivial typo in README.md

tests/test_items.py, tests/test_toml_document.py, tests/util.py, tomlkit/check.py, tomlkit/container.py, tomlkit/items.py
Adds methods to convert TOMLKit objects to plain python methods
Fixes #43
=> Add unwrap method to recursive convert to plain old python objects

tomlkit/container.py
I was going through the codebase while researching a different issue, and came across this typo. Figured I'd open a small PR to fix it!
Changes:
* Change function name `ends_with_withespace` to `ends_with_whitespace`.
=> Fix typo in function name

docs/quickstart.rst, tests/test_toml_document.py, tomlkit/container.py
- Fix #204 remove empty tables from out-of-order table proxy
- Fix #205 Forbid accessing unsupported methods on outf-of-order table
=> fix: remove empty tables from out-of-order table proxy

tests/test_toml_file.py, tomlkit/toml_file.py
Resolves: #200
With this change, when reading a toml file with consistent line endings, changing the content and writing the content into a file, the result is a file with the same consistent line endings as the input file.
Further, default line endings for Windows when creating a new toml file will be Windows line endings (`"\r\n"`) again.
This change is not perfect, because it only ensures that the written file has consistent line endings. Dumping the changed `TomlDocument` as string still has inconsistent line endings. However, keeping consistent line endings for `TomlDocument` seems to require way more effort since hard coded `"\n"` is used in many places.
=> Keep consistent line endings

tests/test_items.py, tomlkit/items.py
I change the add method for Integrer and add a test from this issue #214  now it's work but i don't know if you need this
=> change items.py to add float and int

tests/test_toml_document.py, tomlkit/container.py
=> fix: don't add header when removing items from a supertable

tests/test_items.py, tomlkit/items.py
The issue is, #218 added a `_group_values` cloud add `Null` into the Array values, but the `Array`'s `list.__init__` didn't ignore this value.
Poetry will `copy.copy` an `Array` item (for e.g. here: https://github.com/python-poetry/poetry-core/blob/main/src/poetry/core/packages/package.py#L290 ), then there will be an extra `Null` object in the values, so that an Array like this:
```
[tool.poetry]
classifiers = [
"a",
"b",
]
```
originally is `["a", "b"]`, after being `copy.copy`ed, will become `[None, "a", "b"]` due to the `Null`. (Please see the testcase I added)
Then it will cause poetry to fail because there is an extra "None" in classifiers. ( https://github.com/laixintao/iredis/runs/7749027851?check_suite_focus=true )
related: https://github.com/sdispater/tomlkit/pull/218
=> bugfix: items.Array __init__ didn't ignore Null that _group_values added.

tomlkit/container.py, tomlkit/items.py, tomlkit/parser.py
When using `tomlkit` in type-annotated projects, some `unwrap()` methods have wrong return-type signatures.
Also running `mypy` in the current source tree reports many errors; this PR tries to fix some low-hanging fruits by introducing type-narrowing with `assert isinstance(...)`.
=> fix: type annotation of unwrap() and datetime parsing

.github/workflows/tests.yml, tests/test_items.py, tomlkit/items.py
=> fix: fix a bug that escape chars are lost after concat with another string

tests/test_write.py, tomlkit/items.py
=> fix: rendering table in nested arrays

CHANGELOG.md, tests/test_toml_document.py, tomlkit/container.py, tomlkit/items.py
=> fix: Clear the existing table header

.github/workflows/tests.yml
Python 3.11 will be on average 22% faster than Python 3.10 so let’s give it a spin... https://www.python.org/download/pre-releases
Related to #237
=> Add Python 3.11 release candidate 2 to the testing

CHANGELOG.md, pyproject.toml, tomlkit/__init__.py
- Fix the type annotation of `unwrap()` and datetime parsing. ([#229](https://github.com/sdispater/tomlkit/issues/229))
- Clear the existing table header when it is adding to another table. ([#230](https://github.com/sdispater/tomlkit/issues/230))
- Fix a bug that escape chars are lost after concat with another string. ([#235](https://github.com/sdispater/tomlkit/issues/235))
- Fix a rendering issue of tables inside arrays or inline tables. ([#236](https://github.com/sdispater/tomlkit/issues/236))
=> Release 0.11.5

tomlkit/toml_file.py
Since `tomlkit` supports Python 3.6 and onwards now, `os.PathLike` can be supported as the additional type for `path` argument in `TOMLFile` constructor. This PR adds the necessary bits.
Signed-off-by: oleg.hoefling <oleg.hoefling@gmail.com>
=> allow broader type for toml file path value

.readthedocs.yaml, docs/api.rst, docs/conf.py, tomlkit/api.py
This patch includes minimal configuration and fixes for the Sphinx warnings, making it possible to make the RTD builds succeed.
Fixes #161
Build log in the fork: https://readthedocs.org/projects/tomlkit-webknjazs-fork/builds/18578470/
Demo: https://tomlkit-webknjazs-fork.readthedocs.io/en/maintenance-rtd-config/
=> Configure Read The Docs

CHANGELOG.md, tests/test_items.py, tomlkit/items.py
=> fix: delete inline table element does not leave trailing sep

tomlkit/api.py
Fixes a partially `Unknown` type error with pyright in `tomlkit.load`
=> Missing type argument on `IO`

.pre-commit-config.yaml, pyproject.toml, tests/test_toml_document.py, tomlkit/_compat.py, tomlkit/_utils.py, tomlkit/api.py, tomlkit/container.py, tomlkit/exceptions.py, tomlkit/items.py, tomlkit/parser.py, tomlkit/source.py
=> fix: Build table with dotted key correctly

CHANGELOG.md, pyproject.toml, tomlkit/__init__.py
- Remove the extra indentations added when parsing nested sub-tables. ([#256](https://github.com/sdispater/tomlkit/issues/256))
- Ignore the CRLF immediately following a multiple basic string opening. ([#262](https://github.com/sdispater/tomlkit/issues/262))
- Stringifying subtables and nested tables in arrays of tables. ([#283](https://github.com/sdispater/tomlkit/issues/283))
- Messed table structure when building a table with dotted keys. ([#284](https://github.com/sdispater/tomlkit/issues/284))
=> Release 0.11.8

tests/test_items.py, tomlkit/__init__.py, tomlkit/api.py, tomlkit/items.py
=> feat: allow users to register custom encoders

README.md
For the Quickstart it doesn't make a huge difference, but it is important for the API documentation.
=> README: Link to readthedocs for the documentation

tests/test_items.py
=> fix: replace deprecated usage of datetime.utcnow

tests/test_items.py, tomlkit/items.py
This is a possible fix for https://github.com/sdispater/tomlkit/issues/309. Changes introduced in https://github.com/sdispater/tomlkit/pull/307 made it so that the float result of division on an Integer is wrapped as an Integer, which is incorrect.
I have included a test case which demonstrates the issue.
=> Fix division for integers

tomlkit/container.py, tomlkit/items.py
=> [DOC] Add some docstrings

tomlkit/container.py
=> fix: Newline lost when updating a table

CHANGELOG.md, tomlkit/_types.py
=> fix: `|=` does not work as expected on TOMLDocument

CHANGELOG.md, tomlkit/items.py
=> fix: don't add sign if the float is negative

CHANGELOG.md, tests/test_items.py, tomlkit/container.py
=> fix: Construction of OutOfOrderTableProxy can cause newlines to be inserted

CHANGELOG.md, tests/test_items.py, tomlkit/container.py
This reverts commit c2611c555261e41e1219a675cef14dd24229c607.
Resolve #351
=> fix: Revert "fix: Construction of OutOfOrderTableProxy can cause newlines to be inserted (#347)"

.github/workflows/tests.yml
1. Update cache action version
2. Remove quotes around 3.11
3. Use map to replace list comprehension
=> Update tests action

CHANGELOG.md, tomlkit/exceptions.py, tomlkit/items.py
=> fix: `tomlkit` 0.12.5 : Encoder contract interferes with external `TypeError`s raised in encoders

CHANGELOG.md, tests/test_toml_document.py, tomlkit/container.py
=> fix: keep the nested out of order table

tomlkit/api.py
Since #358, custom encoders are expected to raise a ConvertError instead of a TypeError, but the docstring of register_encoder still mentions TypeError. Fix this to mention ConvertError instead.
=> fix: register encoder's doc incorrectly mentions TypeError

tests/test_toml_file.py, tomlkit/toml_file.py
Fixes: #401 
Converts `\r\n` back to `\n` when reading TOML files.
=> Fix: Inconsistent newlines on Windows

tests/test_toml_file.py
[pytest recommends using `tmp_path` instead.](https://docs.pytest.org/en/7.4.x/how-to/tmp_path.html#the-tmpdir-and-tmpdir-factory-fixtures)
=> Replace pytest's legacy `tmpdir` fixture with `tmp_path`

tests/test_items.py, tomlkit/parser.py
Fixes: #405
This prevents the trailing whitespace on an item from being incorrectly grouped.
```python
>>> from tomlkit import parse
>>> doc = parse('x = [\n    "foo" ,#spam\n    "bar",\n]')
>>> print(repr(doc["x"]))
[
(<Whitespace '\n    '>, 'foo'),
(<Whitespace ' '>, <Null>, <Whitespace ','>, <Comment 'spam'>),
(<Whitespace '\n    '>, 'bar', <Whitespace ','>),
(<Whitespace '\n'>,)
]
[
(<Whitespace '\n    '>, 'foo', <Whitespace ' ,'>, <Comment 'spam'>),
(<Whitespace '\n    '>, 'bar', <Whitespace ','>),
(<Whitespace '\n'>,)
]
```
```python
>>> doc["x"].remove("foo")
>>> print(doc.as_string())
```
```toml
x = [,#spam
"bar",
]
x = [
"bar",
]
```
=> Prevent repeated whitespace items in arrays

tests/test_items.py, tomlkit/items.py
AOT did  not implement __setitem__ and it looked like an oversight.
Tried to implement it add added tests to the best of my understanding, checking that the types returned after setting value, maps or array or of the proper type and properly unwrapped.
=> Aot __setitem__ not implemented fix

tests/test_items.py, tomlkit/items.py, tomlkit/parser.py
=> Fix removal of items from `Array`s

tests/test_toml_document.py, tomlkit/items.py
Fixes #412 
As per the spec, int keys are allowed but should be treated as strings, therefore, we just cast it to a string if it isn't one.
=> Fix: reject single keys that aren't strings

CHANGELOG.md, tests/test_toml_document.py, tomlkit/container.py
=> fix: Missing newline at end of file with multiple array of tables can corrupt during dumping

tests/test_toml_document.py, tomlkit/container.py
When a table is already a super table, appending dotted items to it will result in wrong behavior. The header was missing, so the final result was an incorrect representation of the document.
Because super_table is already set and can no longer be re-evaluated, I have added a check to the renderer instead, so that it can determine if the header should be rendered.
I have not gone through different edge cases, but it seems that all other tests are still passing.
=> fix: Add DottedKey to a super table gives wrong output (#431)
